name = "TBA"
author = "Slash"
version = "1.0.6"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bfefe4dbe930958ee75441669613817ebc62684ab7004e6140be4a495cf1f3b1"

[versions]
fabric = "0.18.3"
minecraft = "1.21.1"
